<?php
declare(strict_types=1);

// Proxyscrape SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ProxyscrapeUtility::setRegistrar(function (ProxyscrapeUtility $u): void {
    $u->clean = [ProxyscrapeClean::class, 'call'];
    $u->done = [ProxyscrapeDone::class, 'call'];
    $u->make_error = [ProxyscrapeMakeError::class, 'call'];
    $u->feature_add = [ProxyscrapeFeatureAdd::class, 'call'];
    $u->feature_hook = [ProxyscrapeFeatureHook::class, 'call'];
    $u->feature_init = [ProxyscrapeFeatureInit::class, 'call'];
    $u->fetcher = [ProxyscrapeFetcher::class, 'call'];
    $u->make_fetch_def = [ProxyscrapeMakeFetchDef::class, 'call'];
    $u->make_context = [ProxyscrapeMakeContext::class, 'call'];
    $u->make_options = [ProxyscrapeMakeOptions::class, 'call'];
    $u->make_request = [ProxyscrapeMakeRequest::class, 'call'];
    $u->make_response = [ProxyscrapeMakeResponse::class, 'call'];
    $u->make_result = [ProxyscrapeMakeResult::class, 'call'];
    $u->make_point = [ProxyscrapeMakePoint::class, 'call'];
    $u->make_spec = [ProxyscrapeMakeSpec::class, 'call'];
    $u->make_url = [ProxyscrapeMakeUrl::class, 'call'];
    $u->param = [ProxyscrapeParam::class, 'call'];
    $u->prepare_auth = [ProxyscrapePrepareAuth::class, 'call'];
    $u->prepare_body = [ProxyscrapePrepareBody::class, 'call'];
    $u->prepare_headers = [ProxyscrapePrepareHeaders::class, 'call'];
    $u->prepare_method = [ProxyscrapePrepareMethod::class, 'call'];
    $u->prepare_params = [ProxyscrapePrepareParams::class, 'call'];
    $u->prepare_path = [ProxyscrapePreparePath::class, 'call'];
    $u->prepare_query = [ProxyscrapePrepareQuery::class, 'call'];
    $u->graphql_body = [ProxyscrapeGraphql::class, 'body'];
    $u->graphql_errors = [ProxyscrapeGraphql::class, 'errors'];
    $u->result_basic = [ProxyscrapeResultBasic::class, 'call'];
    $u->result_body = [ProxyscrapeResultBody::class, 'call'];
    $u->result_headers = [ProxyscrapeResultHeaders::class, 'call'];
    $u->transform_request = [ProxyscrapeTransformRequest::class, 'call'];
    $u->transform_response = [ProxyscrapeTransformResponse::class, 'call'];
});
